[package]
name = "pack-it"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
arrow2 = { version = "0.8", features = ["io_parquet", "io_parquet_compression"] }
crossbeam-channel = "0.5"
log = "0.4"
